#!/bin/bash -e

my_file="$(readlink -e "$0")"
my_dir="$(dirname "$my_file")"

if ! python=$(which python) ; then
  if ! python=$(which python3); then
      echo "ERROR: Can't find python/python3. Failed to run python script vrouter-port-control $@"
      exit 1
  fi
fi

$python $my_dir/vrouter-port-control.py $@
